limit_req_zone $binary_remote_addr zone=sudharma_mainnet_rpc:10m rate=20r/s;

server {
    listen 443 ssl http2;
    server_name mainnet.rpc.REPLACE_WITH_REAL_DOMAIN;

    client_max_body_size 1m;

    location = /v1/status {
        limit_req zone=sudharma_mainnet_rpc burst=40 nodelay;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 3s;
        proxy_read_timeout 15s;
        proxy_pass http://127.0.0.1:28545/v1/status;
    }

    location = /v1/mining/work {
        limit_req zone=sudharma_mainnet_rpc burst=40 nodelay;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 3s;
        proxy_read_timeout 30s;
        proxy_pass http://127.0.0.1:28545/v1/mining/work;
    }

    location = /v1/mining/submit {
        limit_req zone=sudharma_mainnet_rpc burst=40 nodelay;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        client_max_body_size 1m;
        proxy_connect_timeout 3s;
        proxy_read_timeout 30s;
        proxy_pass http://127.0.0.1:28545/v1/mining/submit;
    }
}
